tabuada =  int(input('Digite um número para ver sua tabuada: '))
print('-'*20)
print('{} x 1 = {}'.format(tabuada,(tabuada*1)))
print('{} x 2 = {}'.format(tabuada,(tabuada*2)))
print('{} x 3 = {}'.format(tabuada,(tabuada*3)))
print('{} x 4 = {}'.format(tabuada,(tabuada*4)))
print('{} x 5 = {}'.format(tabuada,(tabuada*5)))
print('{} x 6 = {}'.format(tabuada,(tabuada*6)))
print('{} x 7 = {}'.format(tabuada,(tabuada*7)))
print('{} x 8 = {}'.format(tabuada,(tabuada*8)))
print('{} x 9 = {}'.format(tabuada,(tabuada*9)))
print('{} x 10 = {}'.format(tabuada,(tabuada*10)))
print('-'*20)


